version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.29.0.2
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'files'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'qwe'
      MYSQL_ROOT_PASSWORD: 'qwe'
    networks:
      my_network:
        ipv4_address: 172.29.0.3

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
